//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMessage
    {
        public int Id { get; set; }
        public string SendId { get; set; }
        public string ReceiveId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Atachment { get; set; }
        public System.DateTime SendTime { get; set; }
        public bool IsRead { get; set; }
    }
}
