//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AnswerSheet
    {
        public T_AnswerSheet()
        {
            this.T_AnswerSheetComment = new HashSet<T_AnswerSheetComment>();
            this.T_ChoiceAnswerSheet = new HashSet<T_ChoiceAnswerSheet>();
            this.T_BriefAnswerSheet = new HashSet<T_BriefAnswerSheet>();
        }
    
        public int ID { get; set; }
        public int InterviewerID { get; set; }
        public int PaperID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ICollection<T_AnswerSheetComment> T_AnswerSheetComment { get; set; }
        public virtual T_InterviewerInfo T_InterviewerInfo { get; set; }
        public virtual T_Paper T_Paper { get; set; }
        public virtual ICollection<T_ChoiceAnswerSheet> T_ChoiceAnswerSheet { get; set; }
        public virtual ICollection<T_BriefAnswerSheet> T_BriefAnswerSheet { get; set; }
    }
}
