//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Department
    {
        public T_Department()
        {
            this.T_MemberInformation = new HashSet<T_MemberInformation>();
            this.T_MemberInformation1 = new HashSet<T_MemberInformation>();
        }
    
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<T_MemberInformation> T_MemberInformation { get; set; }
        public virtual ICollection<T_MemberInformation> T_MemberInformation1 { get; set; }
    }
}
