//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InterviewerInfo
    {
        public T_InterviewerInfo()
        {
            this.T_AnswerSheet = new HashSet<T_AnswerSheet>();
        }
    
        public int ID { get; set; }
        public string Num { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Academy { get; set; }
        public string Major { get; set; }
        public string Class { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string TelNum { get; set; }
        public string LearningExperience { get; set; }
        public string SelfEvaluation { get; set; }
        public bool IsRequestTech { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual ICollection<T_AnswerSheet> T_AnswerSheet { get; set; }
    }
}
