//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MemberInformation
    {
        public T_MemberInformation()
        {
            this.T_MemberInformation1 = new HashSet<T_MemberInformation>();
            this.T_MemberInformation11 = new HashSet<T_MemberInformation>();
            this.T_OgnizationAct = new HashSet<T_OgnizationAct>();
            this.T_OnDuty = new HashSet<T_OnDuty>();
            this.T_ProjectInformation = new HashSet<T_ProjectInformation>();
            this.T_ProjectInformation1 = new HashSet<T_ProjectInformation>();
            this.T_RoleAct = new HashSet<T_RoleAct>();
        }
    
        public string StuNum { get; set; }
        public string StuName { get; set; }
        public string Gender { get; set; }
        public string QQNum { get; set; }
        public string Email { get; set; }
        public string LoginPwd { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PhotoPath { get; set; }
        public string Class { get; set; }
        public System.DateTime JoinTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Major { get; set; }
        public string Counselor { get; set; }
        public string HeadTeacher { get; set; }
        public string UndergraduateTutor { get; set; }
        public string TelephoneNumber { get; set; }
        public string HomPhoneNumber { get; set; }
        public string FamilyAddress { get; set; }
        public int Department { get; set; }
        public int TechnicalLevel { get; set; }
        public string StudyGuideNumber { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDelete { get; set; }
        public string Sign { get; set; }
        public string OtheInfor { get; set; }
        public int SecretShow { get; set; }
    
        public virtual T_Department T_Department { get; set; }
        public virtual T_Department T_Department1 { get; set; }
        public virtual ICollection<T_MemberInformation> T_MemberInformation1 { get; set; }
        public virtual T_MemberInformation T_MemberInformation2 { get; set; }
        public virtual ICollection<T_MemberInformation> T_MemberInformation11 { get; set; }
        public virtual T_MemberInformation T_MemberInformation3 { get; set; }
        public virtual T_TechnicaLevel T_TechnicaLevel { get; set; }
        public virtual T_TechnicaLevel T_TechnicaLevel1 { get; set; }
        public virtual ICollection<T_OgnizationAct> T_OgnizationAct { get; set; }
        public virtual ICollection<T_OnDuty> T_OnDuty { get; set; }
        public virtual ICollection<T_ProjectInformation> T_ProjectInformation { get; set; }
        public virtual ICollection<T_ProjectInformation> T_ProjectInformation1 { get; set; }
        public virtual ICollection<T_RoleAct> T_RoleAct { get; set; }
    }
}
