//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProjectType
    {
        public T_ProjectType()
        {
            this.T_ProjectInformation = new HashSet<T_ProjectInformation>();
        }
    
        public int ProjTypeId { get; set; }
        public string ProjTypeName { get; set; }
    
        public virtual ICollection<T_ProjectInformation> T_ProjectInformation { get; set; }
    }
}
