//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QuestionType
    {
        public T_QuestionType()
        {
            this.T_Question = new HashSet<T_Question>();
        }
    
        public int ID { get; set; }
        public string QuestionTypeName { get; set; }
    
        public virtual ICollection<T_Question> T_Question { get; set; }
    }
}
