//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Question
    {
        public T_Question()
        {
            this.T_BriefAnswerSheet = new HashSet<T_BriefAnswerSheet>();
            this.T_ChoiceAnswerSheet = new HashSet<T_ChoiceAnswerSheet>();
            this.T_PaperQuestion = new HashSet<T_PaperQuestion>();
            this.T_QuestionOption = new HashSet<T_QuestionOption>();
        }
    
        public int ID { get; set; }
        public string QuestionContent { get; set; }
        public int QuestionTypeID { get; set; }
        public bool IsDel { get; set; }
        public Nullable<int> QuestionGrade { get; set; }
        public string QuestionTag { get; set; }
    
        public virtual ICollection<T_BriefAnswerSheet> T_BriefAnswerSheet { get; set; }
        public virtual ICollection<T_ChoiceAnswerSheet> T_ChoiceAnswerSheet { get; set; }
        public virtual ICollection<T_PaperQuestion> T_PaperQuestion { get; set; }
        public virtual T_QuestionType T_QuestionType { get; set; }
        public virtual ICollection<T_QuestionOption> T_QuestionOption { get; set; }
    }
}
