//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Role
    {
        public T_Role()
        {
            this.T_RoleAct = new HashSet<T_RoleAct>();
            this.T_RolePermission = new HashSet<T_RolePermission>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<T_RoleAct> T_RoleAct { get; set; }
        public virtual ICollection<T_RolePermission> T_RolePermission { get; set; }
    }
}
