//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RoleAct
    {
        public int RoleId { get; set; }
        public string RoleActor { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual T_MemberInformation T_MemberInformation { get; set; }
        public virtual T_Role T_Role { get; set; }
    }
}
