//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TaskInformation
    {
        public int TaskId { get; set; }
        public string TaskSender { get; set; }
        public string TaskName { get; set; }
        public int TaskTypeId { get; set; }
        public string TaskContent { get; set; }
        public System.DateTime TaskBegTime { get; set; }
        public System.DateTime TaskEndTime { get; set; }
        public Nullable<System.DateTime> TaskFinishTime { get; set; }
        public int ProjId { get; set; }
        public int ProjPhaseId { get; set; }
        public string TaskAttachmentPath { get; set; }
        public string StandbyB { get; set; }
    
        public virtual T_ProjectInformation T_ProjectInformation { get; set; }
        public virtual T_ProjPhase T_ProjPhase { get; set; }
        public virtual T_TaskType T_TaskType { get; set; }
    }
}
