//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TeacherInfo
    {
        public T_TeacherInfo()
        {
            this.T_AnswerSheetComment = new HashSet<T_AnswerSheetComment>();
            this.T_BriefScore = new HashSet<T_BriefScore>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<T_AnswerSheetComment> T_AnswerSheetComment { get; set; }
        public virtual ICollection<T_BriefScore> T_BriefScore { get; set; }
    }
}
