//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User_Message
    {
        public int Id { get; set; }
        public string ReceiveId { get; set; }
        public string SendId { get; set; }
        public int MessageId { get; set; }
        public bool IsRead { get; set; }
        public bool ReceiveIsDelete { get; set; }
        public bool IsDraft { get; set; }
        public bool SendIsDelete { get; set; }
        public Nullable<bool> SendTrueDel { get; set; }
        public Nullable<bool> RecTrueDel { get; set; }
    
        public virtual Tbl_Message Tbl_Message { get; set; }
    }
}
